# -*- coding: utf-8 -*-
"""One-line descriptions for every post, used on cards and category pages."""

EXCERPTS = {
# ---------------------------------------------------- Bodyweight Strength
'bodyweight-strength-training-at-home': "Everything that actually matters about getting strong without weights: progression, volume, frequency, and where bodyweight training genuinely falls short.",
'bodyweight-exercise-progressions': "The full ladder for every major movement, from the easiest regression to the hardest variation, with criteria for when to move up.",
'perfect-push-up-form': "Hand position, elbow angle, and the sagging hips that turn a chest exercise into a lower-back exercise.",
'push-up-progressions-for-beginners': "Six stages from wall to floor, each with a clear graduation test, and no “just do knee push-ups forever”.",
'build-chest-without-weights': "How to keep loading the chest once regular push-ups stop being hard, using leverage instead of plates.",
'bodyweight-squat-form': "How deep is deep enough, whether knees over toes matters, and what to do if your heels lift.",
'bulgarian-split-squat-at-home': "The hardest leg exercise you can do with a sofa, plus how to set the height without wrecking your knee.",
'leg-workout-no-equipment': "A complete lower-body session using only bodyweight, built around single-leg work because two legs stop being hard quickly.",
'pistol-squat-progression': "A realistic twelve-week path to a full single-leg squat, including the mobility work most guides skip.",
'first-pull-up-at-home': "What to do when you cannot yet do one, using a doorway bar, a table, and a lot of patience.",
'back-exercises-no-equipment': "Training the pulling muscles with no bar and no bands — which options work, and which are wishful thinking.",
'rows-at-home': "Seven ways to load a rowing pattern with furniture you already own, ranked by how much resistance they actually give.",
'core-training-without-situps': "Ten exercises that train the core to resist movement rather than create it, which is what it does in real life.",
'plank-progression': "A staged chart from a twenty-second hold to five minutes, and why chasing time alone stops working.",
'bodyweight-shoulder-workout': "Building shoulders that are strong overhead and stable, without a single dumbbell.",
'handstand-progression-beginners': "Wall walks to freestanding, broken into steps you can practise in a hallway without falling into anything.",
'dips-at-home': "Chairs, counters and worktops: safe setups, unsafe ones, and how to scale dips for beginners.",
'glute-exercises-at-home': "Why the machines are not the point, and which bodyweight movements load the glutes hardest.",
'bodyweight-arm-workout': "Direct arm work with no weights — what is possible, what is limited, and how to get the most from it.",
'build-muscle-bodyweight-only': "What the research actually says about hypertrophy without external load, including where the ceiling is.",

# ---------------------------------------------------- Quick Workouts & Plans
'short-workouts-guide': "How to build a genuinely effective session in under thirty minutes: what to cut, what to protect, and what the evidence supports.",
'4-week-home-workout-plan': "Twelve sessions, no equipment, and a progression that assumes you will miss a day — because you will.",
'15-minute-full-body-workout': "Six movements, three rounds, one timer. Built to be genuinely hard in fifteen minutes rather than pleasantly busy for forty.",
'10-minute-morning-workout': "A short session designed to wake the body up rather than exhaust it before the day starts.",
'20-minute-hiit-no-jumping': "Interval training that gets your heart rate genuinely high with both feet staying on the floor.",
'5-minute-workouts-worth-it': "Whether very short sessions do anything measurable, and the specific conditions under which they do.",
'3-day-home-workout-split': "The most defensible way to divide the week when you can train three times, with the full schedule.",
'push-pull-legs-at-home': "Running the classic split with no equipment — which day suffers most, and how to fix it.",
'upper-lower-split-at-home': "A four-day structure for people who want more frequency without longer sessions.",
'how-to-structure-a-home-workout': "The order of operations from warm-up to cool-down, and why exercise sequence changes your results.",
'full-body-vs-split-short-workouts': "When you only have twenty minutes, one of these is clearly better. Here is which, and why.",
'lunch-break-workout': "Twenty minutes of real training that will not leave you unable to return to your desk.",
'home-workout-for-weight-loss': "An eight-week plan built on the honest premise that exercise is the smaller half of fat loss.",
'30-minute-workout-for-parents': "A strength session designed around interruption, so a stopped set does not end the workout.",
'workout-finishers': "Four-minute finishers that add real stimulus to the end of a session without adding twenty minutes.",
'emom-workouts-at-home': "Every-minute-on-the-minute training explained, with three ready-made bodyweight versions.",
'circuit-training-at-home': "How to build a circuit that trains strength rather than turning into unstructured cardio.",
'how-many-days-a-week-workout': "What the evidence says about frequency, and why more days is not reliably better.",
'deload-week-home-training': "Whether bodyweight trainees need deloads at all, and how to run one if you do.",
'weekly-home-workout-schedule': "A week-by-week template you can actually keep, with the rest days treated as part of the plan.",

# ---------------------------------------------------- Small-Space & Quiet
'small-apartment-workout-guide': "Layout, noise, flooring, storage and neighbours — the complete guide to training in a flat.",
'quiet-home-workouts': "Every jumping exercise, replaced. A full noise-free substitution table for training above someone else's ceiling.",
'no-jump-cardio': "Twelve ways to raise your heart rate without your downstairs neighbour learning your schedule.",
'apartment-friendly-hiit': "High-intensity intervals redesigned for upstairs flats, thin floors and sleeping housemates.",
'how-much-space-to-work-out': "The actual floor area each common exercise needs, measured, so you can plan around your room.",
'low-ceiling-workouts': "What to do when you cannot press or jump overhead, and which exercises replace the ones you lose.",
'hotel-room-workout': "Twenty minutes, no equipment, and nothing that will annoy the room below you.",
'office-workout': "Movement you can do in work clothes without needing a shower afterwards.",
'exercise-mat-for-noise-reduction': "Which mats actually dampen impact noise, what thickness matters, and where thicker becomes worse.",
'workout-at-home-with-kids': "Session structures built for interruption, plus the exercises that survive a toddler climbing on you.",
'home-gym-corner-small-space': "Setting up a usable training corner in a one-bedroom without it taking over the room.",
'silent-ab-workout': "Core training that makes no noise at all, for shared walls and late nights.",
'carpet-vs-hard-floor-workout': "How your surface changes stability, joint load and which exercises are safe to do.",
'balcony-workout': "Making use of a small outdoor space, including what not to do on a shared balcony.",
'stair-workouts': "Turning the one piece of equipment your building already gave you into real training.",
'storing-home-gym-equipment': "Where to put your kit in a tiny flat so it stays accessible enough that you keep using it.",
'bedroom-workout-quiet': "A full session you can do beside a sleeping partner without waking them.",
'standing-workout-no-floor': "A complete workout with no getting up and down, for bad knees, small rooms and dirty floors.",
'travel-workout-routine': "A routine that fits in a carry-on, works in any room, and needs no booking.",
'studio-flat-workout-setup': "A real walkthrough of arranging a studio so training does not mean moving furniture every time.",

# ---------------------------------------------------- Minimal Gear
'minimalist-home-gym-guide': "Four purchases cover roughly ninety per cent of what a home trainee needs. Here they are, in buying order.",
'resistance-bands-guide': "Types, strengths, anchoring, and how to progress with bands once the light one is easy.",
'resistance-band-full-body-workout': "A twenty-minute session using one set of bands, covering every major movement pattern.",
'loop-bands-vs-tube-bands': "The practical differences that matter, and which one to buy first if you are only buying one.",
'one-dumbbell-workout': "If you own exactly one weight, this is the most you can get out of it.",
'adjustable-dumbbells-buying-guide': "What to look for on a budget, which mechanisms fail, and when fixed weights are the better buy.",
'doorway-pull-up-bar-guide': "Fit, safety, weight limits and the door frames these genuinely should not be used on.",
'gymnastic-rings-at-home': "Where to hang them, what they let you train, and the first month of workouts.",
'furniture-sliders-workout': "The cheapest piece of equipment worth owning, and the core and leg exercises it unlocks.",
'kettlebell-vs-dumbbell-home': "Which single implement gives a small home setup more, depending on what you want to train.",
'cheap-home-gym-equipment': "The equipment worth owning under fifty pounds or dollars, and what to skip at any price.",
'diy-home-gym-equipment': "Loading exercises with a rucksack, water containers and a towel — what works and what is unsafe.",
'suspension-trainer-home-review': "Whether a suspension trainer earns its price at home, and who it genuinely suits.",
'jump-rope-alternatives': "Getting the conditioning benefit of a rope without the ceiling height or the noise.",
'weighted-vest-training': "Who a weighted vest actually helps, at what point it makes sense, and how to load it.",
'ab-wheel-progression': "A staged progression to a standing rollout, and an honest answer on whether you need one.",
'yoga-mat-vs-exercise-mat': "Thickness, grip, durability and noise — which mat suits which kind of training.",
'best-home-workout-apps': "Which apps are genuinely useful for home training, and which are a subscription for a timer.",
'do-you-need-a-workout-bench': "What a bench unlocks, what substitutes for it, and whether the floor space is worth it.",
'home-gym-under-100': "A complete shopping list under a hundred, chosen so nothing on it is redundant.",

# ---------------------------------------------------- Habits & Recovery
'stick-to-home-workout-habit': "Motivation is not the variable worth optimising. What behaviour research says about friction, cues and the two-day rule.",
'recovery-for-busy-people': "Sleep, soreness and rest days for people who cannot build a life around recovery.",
'home-workout-motivation': "Why motivation reliably fails as a strategy, and what to build instead.",
'habit-stacking-exercise': "Attaching a workout to something you already do without fail, and why that works better than scheduling.",
'restart-after-missing-workouts': "How to come back after two weeks off without either overdoing it or quietly quitting.",
'morning-vs-evening-workouts': "What the evidence says about timing, and why the answer is mostly about your schedule.",
'5-minute-warm-up': "A short warm-up that covers what warm-ups are actually for, without eating your session.",
'cool-down-stretches': "What stretching after training does and does not do, plus a five-minute sequence worth keeping.",
'doms-muscle-soreness': "Soreness is not a scorecard. What the evidence supports for relief, and what is folklore.",
'mobility-routine-desk-workers': "A short daily routine targeting the specific things sitting all day actually does to you.",
'foam-rolling-evidence': "What foam rolling is measurably good for, what it is not, and how long to spend on it.",
'protein-for-home-workouts': "How much protein bodyweight training actually needs, and how to hit it without tracking everything.",
'high-protein-quick-meals': "Meals you can make in fifteen minutes that hit a real protein target, not a token one.",
'pre-and-post-workout-nutrition': "Whether the anabolic window is real, and what genuinely matters around a home session.",
'sleep-and-strength-training': "How sleep debt affects strength, recovery and appetite, with the research behind it.",
'tracking-progress-at-home': "Measuring progress without a barbell or a scale, using numbers you already have.",
'how-long-to-see-results': "A realistic timeline for strength, muscle and visible change, week by week.",
'working-out-when-tired': "A decision rule for train-or-skip that is more useful than “listen to your body”.",
'six-week-drop-off': "Why week six is where most home training dies, and the specific things that prevent it.",
'workout-routine-shift-work': "Building a training routine around rotating shifts, night work and permanently disrupted sleep.",
}
