# -*- coding: utf-8 -*-
"""Blueprint exercise diagrams, drawn from scratch as SVG.

Every image on this site is original line art generated by this file. Nothing is
sourced from a stock library, so there is no licence to honour, no attribution
to carry, and no takedown risk.

Coordinates are a 0-100 square; `box()` maps that into the image. Side-on view
throughout, the way a printed exercise manual draws it.
"""

# The palette is module-level and swapped per image by set_pillar(), so a
# diagram lands in the same colour as the section it belongs to.
PAPER, INK, NAVY = '#FDFCFA', '#14161A', '#14161A'
ACCENT, YELLOW = '#3A32A8', '#FFC933'
LINE, LINE_STRONG, MUTED = '#E5E1D9', '#C7C1B6', '#5E646D'
FAR = '#A7A29A'          # limbs on the far side of the body

PILLAR_COLOURS = {
 'bodyweight-strength':  ('#C62F27', '#FDECEA'),
 'quick-workouts':       ('#0A7365', '#E3F5F2'),
 'small-space-training': ('#5C3BD6', '#EDE8FD'),
 'minimal-gear':         ('#A96504', '#FDF0DC'),
 'habits-recovery':      ('#268543', '#E6F5EA'),
}


def set_pillar(name):
    """Point ACCENT and the paper ground at one section's colour.

    Called once per image before composing. The deep tone is used rather than
    the vivid one because these marks are small on a light ground.
    """
    global ACCENT, PAPER
    ACCENT, PAPER = PILLAR_COLOURS.get(name, ('#3A32A8', '#FDFCFA'))

# --- poses -----------------------------------------------------------------
# Joints: head (centre), neck, shoulder, elbow, wrist, hip, knee, ankle, toe.
# 'far' overrides joints for the limbs drawn behind the torso.
POSES = {
 'stand':      dict(head=(54,11), neck=(51,20), shoulder=(50,25), elbow=(56,39), wrist=(59,52),
                    hip=(50,53), knee=(50,71), ankle=(50,89), toe=(58,89)),
 'squat-top':  dict(head=(54,13), neck=(51,22), shoulder=(50,27), elbow=(58,38), wrist=(66,43),
                    hip=(50,55), knee=(50,72), ankle=(50,89), toe=(58,89)),
 'squat-bot':  dict(head=(60,34), neck=(57,42), shoulder=(55,46), elbow=(63,54), wrist=(71,56),
                    hip=(42,66), knee=(63,73), ankle=(47,89), toe=(57,89)),
 'pushup-top': dict(head=(77,53), neck=(72,55), shoulder=(70,56), elbow=(70,72), wrist=(70,88),
                    hip=(44,65), knee=(30,70), ankle=(14,76), toe=(12,88)),
 'pushup-bot': dict(head=(77,72), neck=(72,73), shoulder=(70,74), elbow=(80,80), wrist=(70,88),
                    hip=(44,80), knee=(30,83), ankle=(14,86), toe=(12,88)),
 'pushup-sag':  dict(head=(77,53), neck=(72,55), shoulder=(70,56), elbow=(70,72), wrist=(70,88),
                    hip=(44,76), knee=(30,77), ankle=(14,78), toe=(12,88)),
 'pushup-pike': dict(head=(77,53), neck=(72,55), shoulder=(70,56), elbow=(70,72), wrist=(70,88),
                    hip=(44,48), knee=(30,64), ankle=(14,80), toe=(12,88)),
 'plank':      dict(head=(77,57), neck=(72,58), shoulder=(70,60), elbow=(70,88), wrist=(82,88),
                    hip=(44,70), knee=(30,76), ankle=(14,82), toe=(12,88)),
 'side-plank': dict(head=(73,46), neck=(68,48), shoulder=(66,50), elbow=(66,69), wrist=(66,88),
                    hip=(44,68), knee=(30,77), ankle=(16,86), toe=(12,90),
                    far=dict(elbow=(60,36), wrist=(56,20))),
 'lunge':      dict(head=(47,17), neck=(45,26), shoulder=(44,31), elbow=(44,45), wrist=(44,58),
                    hip=(44,57), knee=(62,72), ankle=(62,89), toe=(70,89),
                    far=dict(knee=(28,78), ankle=(20,89), toe=(14,86))),
 'hinge':      dict(head=(72,32), neck=(67,36), shoulder=(64,40), elbow=(64,54), wrist=(64,66),
                    hip=(40,50), knee=(44,70), ankle=(46,89), toe=(54,89)),
 'bridge':     dict(head=(16,84), neck=(22,82), shoulder=(26,80), elbow=(20,86), wrist=(14,89),
                    hip=(54,64), knee=(72,74), ankle=(72,89), toe=(80,89)),
 'row':        dict(head=(71,67), neck=(66,68), shoulder=(64,70), elbow=(58,58), wrist=(52,46),
                    hip=(44,78), knee=(29,82), ankle=(14,86), toe=(10,90)),
 'pullup':     dict(head=(53,26), neck=(50,34), shoulder=(50,39), elbow=(58,30), wrist=(50,18),
                    hip=(50,59), knee=(48,75), ankle=(48,90), toe=(56,90)),
 'hang':       dict(head=(53,44), neck=(50,52), shoulder=(50,57), elbow=(53,37), wrist=(50,18),
                    hip=(50,78), knee=(48,93), ankle=(48,107), toe=(56,107)),
 'dip':        dict(head=(52,26), neck=(50,34), shoulder=(50,39), elbow=(48,53), wrist=(50,64),
                    hip=(50,62), knee=(58,77), ankle=(52,89), toe=(60,89)),
 'wall-sit':   dict(head=(37,29), neck=(35,37), shoulder=(34,42), elbow=(40,53), wrist=(48,58),
                    hip=(34,64), knee=(62,64), ankle=(62,89), toe=(70,89)),
 'dead-bug':   dict(head=(20,78), neck=(26,77), shoulder=(30,76), elbow=(38,64), wrist=(46,54),
                    hip=(58,78), knee=(62,62), ankle=(74,58), toe=(80,62)),
 'bird-dog':   dict(head=(69,56), neck=(64,58), shoulder=(62,60), elbow=(62,76), wrist=(62,88),
                    hip=(40,64), knee=(40,76), ankle=(40,88), toe=(46,88),
                    far=dict(elbow=(74,52), wrist=(86,46), knee=(26,58), ankle=(12,52), toe=(6,56))),
 'mtn-climber':dict(head=(77,57), neck=(72,58), shoulder=(70,60), elbow=(70,74), wrist=(70,88),
                    hip=(44,70), knee=(56,76), ankle=(54,86), toe=(60,88),
                    far=dict(knee=(28,78), ankle=(14,86), toe=(10,90))),
 'jack':       dict(head=(50,14), neck=(50,23), shoulder=(50,28), elbow=(36,20), wrist=(24,12),
                    hip=(50,54), knee=(38,71), ankle=(30,89), toe=(26,89),
                    far=dict(elbow=(64,20), wrist=(76,12), knee=(62,71), ankle=(70,89), toe=(74,89))),
 'high-knee':  dict(head=(50,14), neck=(48,23), shoulder=(47,28), elbow=(56,38), wrist=(60,28),
                    hip=(48,54), knee=(64,50), ankle=(60,64), toe=(68,66),
                    far=dict(elbow=(38,38), wrist=(34,48), knee=(46,72), ankle=(46,89), toe=(54,89))),
 'calf-raise': dict(head=(54,12), neck=(51,21), shoulder=(50,26), elbow=(56,40), wrist=(59,53),
                    hip=(50,54), knee=(50,71), ankle=(50,82), toe=(58,89)),
 'superman':   dict(head=(74,72), neck=(69,73), shoulder=(66,75), elbow=(74,68), wrist=(84,62),
                    hip=(42,79), knee=(28,80), ankle=(14,74), toe=(8,70)),
 'crunch':     dict(head=(32,64), neck=(37,67), shoulder=(40,70), elbow=(34,62), wrist=(30,58),
                    hip=(60,80), knee=(74,68), ankle=(78,86), toe=(86,86)),
 'pistol':     dict(head=(44,34), neck=(42,42), shoulder=(41,46), elbow=(50,52), wrist=(60,54),
                    hip=(36,68), knee=(56,76), ankle=(40,89), toe=(50,89),
                    far=dict(knee=(58,64), ankle=(76,58), toe=(84,60))),
 'handstand':  dict(head=(45,73), neck=(48,69), shoulder=(50,66), elbow=(54,77), wrist=(50,88),
                    hip=(50,42), knee=(51,24), ankle=(50,8), toe=(44,4)),
 'sit-tall':   dict(head=(48,28), neck=(46,37), shoulder=(45,42), elbow=(51,54), wrist=(59,58),
                    hip=(42,66), knee=(66,66), ankle=(66,89), toe=(74,89)),
}

LIMBS = [('neck', 'hip'), ('shoulder', 'elbow'), ('elbow', 'wrist'),
         ('hip', 'knee'), ('knee', 'ankle'), ('ankle', 'toe')]


def _bbox(pose):
    pts = [v for k, v in pose.items() if k != 'far']
    pts += list((pose.get('far') or {}).values())
    xs = [p[0] for p in pts]; ys = [p[1] for p in pts]
    return min(xs), min(ys), max(xs), max(ys)


def _fitter_from(bb, box, pad=0.10):
    """Build a transform from an explicit bounding box — lets two poses share one
    scale and one ground line, so a start/finish pair is actually comparable."""
    x0, y0, w, h = box
    px, py = w * pad, h * pad
    ax, ay, bx, by = bb
    sw, sh = max(bx - ax, 1e-6), max(by - ay, 1e-6)
    k = min((w - 2 * px) / sw, (h - 2 * py) / sh)
    ox = x0 + (w - sw * k) / 2.0 - ax * k
    oy = y0 + (h - sh * k) / 2.0 - ay * k
    return (lambda p: (ox + p[0] * k, oy + p[1] * k)), k


def union_bbox(names):
    bs = [_bbox(POSES[n]) for n in names]
    return (min(b[0] for b in bs), min(b[1] for b in bs),
            max(b[2] for b in bs), max(b[3] for b in bs))


def _fitter(pose, box, pad=0.10):
    """Scale a pose to fill `box`, preserving aspect, so every figure reads at
    the same visual weight regardless of how tall or wide its pose happens to be."""
    x0, y0, w, h = box
    px, py = w * pad, h * pad
    ax, ay, bx, by = _bbox(pose)
    sw, sh = max(bx - ax, 1e-6), max(by - ay, 1e-6)
    k = min((w - 2 * px) / sw, (h - 2 * py) / sh)
    ox = x0 + (w - sw * k) / 2.0 - ax * k
    oy = y0 + (h - sh * k) / 2.0 - ay * k
    return (lambda p: (ox + p[0] * k, oy + p[1] * k)), k


def _pt(pose, name, box):
    f, _ = _fitter(pose, box)
    return f(pose[name])


def figure(name, box, stroke=9, bb=None):
    """Return SVG for one posed figure inside `box` = (x, y, w, h).

    Pass `bb` (from union_bbox) to draw several poses at one shared scale."""
    pose = POSES[name]
    far = pose.get('far') or {}
    fit, k = _fitter_from(bb or _bbox(pose), box)
    ax, ay, bx, by = bb or _bbox(pose)
    fig_h = (by - ay) * k              # the figure's drawn height, in px
    out = []

    # far-side limbs first, so the near side reads on top
    if far:
        fp = dict(pose); fp.update(far)
        for a, b in LIMBS:
            if a in far or b in far:
                p, q = fit(fp[a]), fit(fp[b])
                out.append('<line x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f" stroke="%s" '
                           'stroke-width="%.1f" stroke-linecap="round"/>'
                           % (p[0], p[1], q[0], q[1], FAR, stroke * 0.85))

    for a, b in LIMBS:
        p, q = fit(pose[a]), fit(pose[b])
        w = stroke * (1.25 if (a, b) == ('neck', 'hip') else 1.0)
        out.append('<line x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f" stroke="%s" '
                   'stroke-width="%.1f" stroke-linecap="round"/>'
                   % (p[0], p[1], q[0], q[1], NAVY, w))

    hx, hy = fit(pose['head'])
    r = max(fig_h * 0.052, stroke * 1.35)   # head reads against the figure, not the line
    out.append('<circle cx="%.1f" cy="%.1f" r="%.1f" fill="%s"/>' % (hx, hy, r, NAVY))
    return '\n'.join(out)


# --- scene -----------------------------------------------------------------
def tuple_blend(a, b, t):
    """Mix two hex colours, so the grid tints with whatever paper is set."""
    pa = [int(a.lstrip('#')[i:i+2], 16) for i in (0, 2, 4)]
    pb = [int(b.lstrip('#')[i:i+2], 16) for i in (0, 2, 4)]
    return '#%02X%02X%02X' % tuple(round(x + (y - x) * t) for x, y in zip(pa, pb))


def grid(w, h, minor=32, major=160):
    faint = tuple_blend(PAPER, LINE, 0.55)
    out = ['<rect width="%d" height="%d" fill="%s"/>' % (w, h, PAPER)]
    for x in range(0, w, minor):
        out.append('<line x1="%d" y1="0" x2="%d" y2="%d" stroke="%s"/>' % (x, x, h, faint))
    for y in range(0, h, minor):
        out.append('<line x1="0" y1="%d" x2="%d" y2="%d" stroke="%s"/>' % (y, w, y, faint))
    for x in range(0, w, major):
        out.append('<line x1="%d" y1="0" x2="%d" y2="%d" stroke="%s"/>' % (x, x, h, LINE))
    for y in range(0, h, major):
        out.append('<line x1="0" y1="%d" x2="%d" y2="%d" stroke="%s"/>' % (y, w, y, LINE))
    return '\n'.join(out)


def frame(w, h, m=50):
    o = ['<rect x="%d" y="%d" width="%d" height="%d" fill="none" stroke="%s"/>'
         % (m, m, w - 2 * m, h - 2 * m, LINE_STRONG)]
    t = 22
    for cx, cy, sx, sy in ((m, m, 1, 1), (w - m, m, -1, 1), (m, h - m, 1, -1), (w - m, h - m, -1, -1)):
        o.append('<path d="M%d %d H%d M%d %d V%d" stroke="%s" stroke-width="2.5" fill="none"/>'
                 % (cx, cy, cx + t * sx, cx, cy, cy + t * sy, NAVY))
    return '\n'.join(o)


def ground(box, extra=40, pose=None, bb=None):
    """Ground line aligned to the figure's lowest joint, so feet never float."""
    x0, y0, w, h = box
    if pose and pose in POSES:
        fit, _ = _fitter_from(bb or _bbox(POSES[pose]), box)
        y = max(fit(p)[1] for k, p in POSES[pose].items() if k != 'far')
        y = max(y, max([fit(p)[1] for p in (POSES[pose].get('far') or {}).values()] or [y]))
    else:
        y = y0 + h * 0.90
    return ('<line x1="%.0f" y1="%.0f" x2="%.0f" y2="%.0f" stroke="%s" stroke-width="3"/>'
            % (x0 - extra, y, x0 + w + extra, y, LINE_STRONG))


def arrow(x1, y1, x2, y2, colour=None, w=4, dash=False):
    colour = colour or ACCENT
    d = ' stroke-dasharray="9 7"' if dash else ''
    return ('<defs><marker id="a%d" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5.5" '
            'markerHeight="5.5" orient="auto"><path d="M0 0 L10 5 L0 10 z" fill="%s"/></marker></defs>'
            '<line x1="%.0f" y1="%.0f" x2="%.0f" y2="%.0f" stroke="%s" stroke-width="%d"%s '
            'marker-end="url(#a%d)" stroke-linecap="round"/>'
            % (abs(hash((x1, y1, x2, y2))) % 99999, colour, x1, y1, x2, y2, colour, w, d,
               abs(hash((x1, y1, x2, y2))) % 99999))


def label(x, y, text, size=21, colour=None, weight=600, anchor='start', mono=False):
    colour = colour or NAVY
    fam = ("'IBM Plex Mono','DejaVu Sans Mono',monospace" if mono
           else "'Instrument Sans','Archivo','DejaVu Sans',system-ui,sans-serif")
    return ('<text x="%.0f" y="%.0f" font-family="%s" font-size="%d" font-weight="%d" '
            'fill="%s" text-anchor="%s">%s</text>' % (x, y, fam, size, weight, colour, anchor,
                                                      esc(text)))


def eyebrow(x, y, text):
    return ('<rect x="%.0f" y="%.0f" width="12" height="12" fill="%s"/>' % (x, y - 11, ACCENT)
            + label(x + 22, y, text.upper(), size=17, colour=NAVY, weight=700, mono=True))


def esc(s):
    return (s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;'))


def svg(w, h, body):
    return ('<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" viewBox="0 0 %d %d">'
            '%s</svg>' % (w, h, w, h, body))


# Poses that hang from or press on apparatus rather than standing on the floor.
HANGING = {'hang': 'bar', 'pullup': 'bar', 'row': 'bar', 'dip': 'bars'}


def support(box, pose, bb=None, extra=40):
    """Draw the apparatus a pose actually uses.

    A hanging pose given a ground line at its feet reads as someone standing
    with an arm raised, which is why this exists.
    """
    kind = HANGING.get(pose)
    if not kind:
        return ground(box, extra, pose, bb)
    fit, k = _fitter_from(bb or _bbox(POSES[pose]), box)
    wx, wy = fit(POSES[pose]['wrist'])
    x0, y0, w, h = box
    if kind == 'bar':
        return ('<line x1="%.0f" y1="%.0f" x2="%.0f" y2="%.0f" stroke="%s" '
                'stroke-width="7" stroke-linecap="round"/>'
                % (x0 - extra * 0.4, wy, x0 + w + extra * 0.4, wy, LINE_STRONG))
    span = w * 0.20
    return ''.join(
        '<line x1="%.0f" y1="%.0f" x2="%.0f" y2="%.0f" stroke="%s" stroke-width="7" '
        'stroke-linecap="round"/>' % (wx + sx * span * 0.25, wy, wx + sx * span, wy, LINE_STRONG)
        for sx in (-1, 1))
